//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SynergyWebServices.BLL.Resource;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class ResourceResponse {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ResourceResponse() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SynergyWebServices.BLL.Resource", typeof(ResourceResponse).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Account Activated.
    /// </summary>
    internal static string AccountActivated {
        get {
            return ResourceManager.GetString("AccountActivated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Item Sucessfully Added.
    /// </summary>
    internal static string AddedSucessfully {
        get {
            return ResourceManager.GetString("AddedSucessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Already Two Exists Please Delete and New Ads.
    /// </summary>
    internal static string AdLimtReached {
        get {
            return ResourceManager.GetString("AdLimtReached", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Approved Sucessfully.
    /// </summary>
    internal static string ApprovedSucessfully {
        get {
            return ResourceManager.GetString("ApprovedSucessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This Bar Code Already Exists In Asset Master.
    /// </summary>
    internal static string BarCodeAlreadyExists {
        get {
            return ResourceManager.GetString("BarCodeAlreadyExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Barcode Not Assigned For This Activity.
    /// </summary>
    internal static string BarcodeNotAssignedForThisActivity {
        get {
            return ResourceManager.GetString("BarcodeNotAssignedForThisActivity", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Barcode Not Found In Asset Libray.
    /// </summary>
    internal static string BarcodeNotFoundInAssetLibray {
        get {
            return ResourceManager.GetString("BarcodeNotFoundInAssetLibray", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to CheckList Created Successfully.
    /// </summary>
    internal static string CheckListCreatedSuccessfully {
        get {
            return ResourceManager.GetString("CheckListCreatedSuccessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This Coupon Is Already Redeemed, Please contact us.
    /// </summary>
    internal static string CouponAlreadyRedeemed {
        get {
            return ResourceManager.GetString("CouponAlreadyRedeemed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Customer Data Already Exists.
    /// </summary>
    internal static string CustomerDataAlreadyExists {
        get {
            return ResourceManager.GetString("CustomerDataAlreadyExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Item Deleted Sucessfully.
    /// </summary>
    internal static string DeletedSucessfully {
        get {
            return ResourceManager.GetString("DeletedSucessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Something Went Wrong.Please Contact System Admin.
    /// </summary>
    internal static string ExceptionMessage {
        get {
            return ResourceManager.GetString("ExceptionMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Some Error Has Occurred.
    /// </summary>
    internal static string FailureMessage {
        get {
            return ResourceManager.GetString("FailureMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to There is a problem in uploading file please try again later.
    /// </summary>
    internal static string FileUploaderFailure {
        get {
            return ResourceManager.GetString("FileUploaderFailure", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to File Uploaded Successfully.
    /// </summary>
    internal static string FileUploaderSuccess {
        get {
            return ResourceManager.GetString("FileUploaderSuccess", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Job Closed Successfully.
    /// </summary>
    internal static string JobClosedSuccessfully {
        get {
            return ResourceManager.GetString("JobClosedSuccessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This Job Is Not Completely Created Please Check.
    /// </summary>
    internal static string JobNotCompletelyCreated {
        get {
            return ResourceManager.GetString("JobNotCompletelyCreated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This Job Not Yet Completed.
    /// </summary>
    internal static string JobNotYetCompleted {
        get {
            return ResourceManager.GetString("JobNotYetCompleted", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Link Error.
    /// </summary>
    internal static string LinkError {
        get {
            return ResourceManager.GetString("LinkError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Link Expired Please Try Again Later.
    /// </summary>
    internal static string LinkTimedOut {
        get {
            return ResourceManager.GetString("LinkTimedOut", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unable To Login Please Try Again Later.
    /// </summary>
    internal static string LoginUnSuccessful {
        get {
            return ResourceManager.GetString("LoginUnSuccessful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Mail Sent Successfully.
    /// </summary>
    internal static string MailSentSuccessful {
        get {
            return ResourceManager.GetString("MailSentSuccessful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Moved Successfully.
    /// </summary>
    internal static string MovedSuccessfully {
        get {
            return ResourceManager.GetString("MovedSuccessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No Items Found.
    /// </summary>
    internal static string NoItemsFound {
        get {
            return ResourceManager.GetString("NoItemsFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No Jobs Assigned For Admin.
    /// </summary>
    internal static string NoJobsAssignedAdmin {
        get {
            return ResourceManager.GetString("NoJobsAssignedAdmin", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No Jobs Assigned For Super Admin.
    /// </summary>
    internal static string NoJobsAssignedSuperAdmin {
        get {
            return ResourceManager.GetString("NoJobsAssignedSuperAdmin", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No Suggestions Found.
    /// </summary>
    internal static string NoSuggestionsFound {
        get {
            return ResourceManager.GetString("NoSuggestionsFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Not An Authorized User.
    /// </summary>
    internal static string NotAuthorizedUser {
        get {
            return ResourceManager.GetString("NotAuthorizedUser", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Password Reset Successful.
    /// </summary>
    internal static string PasswordResetSuccessful {
        get {
            return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Payment not for this order.
    /// </summary>
    internal static string PaymentNotSucessful {
        get {
            return ResourceManager.GetString("PaymentNotSucessful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Payment sucessfully done for this order.
    /// </summary>
    internal static string PaymentSucessful {
        get {
            return ResourceManager.GetString("PaymentSucessful", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Rejected Sucessfully.
    /// </summary>
    internal static string RejectedSucessfully {
        get {
            return ResourceManager.GetString("RejectedSucessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Test Submitted Sucessfully.
    /// </summary>
    internal static string SubmitedSucessfully {
        get {
            return ResourceManager.GetString("SubmitedSucessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This Is Last Question.
    /// </summary>
    internal static string ThisIsLastQuestion {
        get {
            return ResourceManager.GetString("ThisIsLastQuestion", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Total Question Already excided from given total question in Test Master.
    /// </summary>
    internal static string TotalQuestionAlreadyFilled {
        get {
            return ResourceManager.GetString("TotalQuestionAlreadyFilled", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Item Updated Sucessfully.
    /// </summary>
    internal static string UpdatedSucessfully {
        get {
            return ResourceManager.GetString("UpdatedSucessfully", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This UserName Is Already Taken.
    /// </summary>
    internal static string UserAlreadyExists {
        get {
            return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to User Does Not Exists.
    /// </summary>
    internal static string UserDoesNotExists {
        get {
            return ResourceManager.GetString("UserDoesNotExists", resourceCulture);
        }
    }
}
